config/routes.rb
Slam6DUI::Application.routes.draw do

  resources :pointclouds do
    member do
      post 'slam6d_show'
      post 'scale_and_center'
      post 'reduce'
      post 'convert_to_uos'
      post 'get_object'
      post 'multiply_frames'
      
      get 'webgl'
    end
  end
  
  resources :sketchupmodels  do
    member do
      post "resample"
    end
  end
  resources :matchings do
    member do
      post "run"
    end
  end
  
  resources :icps do
    member do
      get 'run'
      get 'view'
    end
  end
  
  resources :scans do
    member do
      post 'segment'
    end
  end

  root :to => "pointclouds#index"

end

app/models/matching.rb
class Matching < ActiveRecord::Base
  belongs_to :pointcloud
  belongs_to :best_model, :class_name => :model
  
  belongs_to :scan
  belongs_to :sketchupmodel
  
  serialize :results
  
  def sorted_results
    return [] if results.nil?
    
    r = results.sort.reject { |r| r[0] < 0 }
    models = []
    results = []
    r.map do |p|
      unless models.include?(p[1])
        results << p
        models << p[1]
      end
    end
    results
  end
  
  def rotation_count
    rotations = ["0 0 0", "0 90 0", "0 180 0", "0 270 0"]
    rotations.map { |r| 
      [r, sorted_results.map { |i| i[2] == r ? 1 : 0 }.sum]
    }
  end
  
  def run
    rotations = ["0 0 0", "0 90 0", "0 180 0", "0 270 0"]
    self.update_attribute(:results, [])
    res = []
    
    if self.category == "best_model"
      sketchups = []
      sketchups += Matching.all.map { |m| m.sorted_results[0..top_models - 1].map { |p| Sketchupmodel.find(p[1]) } }.flatten if top_models    
      sketchups += Sketchupmodel.find_all_by_name(model_name) if model_name
    
      return sketchups.each { |m| rotations.each { |r| self.delay.error_with_model(m, r) } }
    else
      pointclouds = self.scan.pointclouds.reject { |r| !r.name.include?("bounded") }
      
      return pointclouds.each { |p| rotations.each { |r| self.delay.error_with_pointcloud(p, r) }}
    end
  end
  
  def error_with_pointcloud(pointcloud, rotation = "0 0 0")
    sl = Slam6D.new({:first_scan_path => pointcloud.complete_path,
                     :second_scan_path => self.sketchupmodel.pointclouds.last.complete_path,
                     :second_scan_rotation => rotation })
    output = sl.runMatching
    crt_error = output.split("F&A\n")[1].split("\n")[0].to_f
    
    puts "#{pointcloud.id} - #{rotation} - #{crt_error}"
    
    res = Matching.find(self.id).results
    res << [crt_error, pointcloud.id, rotation]
    self.update_attribute(:results, res)
  end
  
  def error_with_model(model, rotation = "0 0 0")
    if model.pointclouds.count < 3
      model.resample(0.0001)
      model = Sketchupmodel.find(model.id)
    end
    
    sl = Slam6D.new({:first_scan_path => pointcloud.complete_path,
                     :second_scan_path => model.pointclouds.last.complete_path,
                     :second_scan_rotation => rotation })
    output = sl.runMatching
    crt_error = output.split("F&A\n")[1].split("\n")[0].to_f
    
    puts "#{model.id} - #{rotation} - #{model.google_id} - #{crt_error}"
    
    res = Matching.find(self.id).results
    res << [crt_error, model.id, rotation]
    self.update_attribute(:results, res)    
  end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController
  before_filter :load_matching, :except => [:index, :new, :create]
  
  def new
    @matching = Matching.new
  end
  
  def create
    @matching = Matching.new(params[:matching])
    if @matching.save
      flash[:notice] = "Matching saved"
      redirect_to @matching
    else
      flash[:notice] = "You have some errors.."
      render :new
    end
  end
  
  def index
    @matchings = Matching.all
  end
  
  def show
    respond_to do |format|
      format.text
      format.html
    end
  end
  
  def run
    @matching.delay.run
    redirect_to @matching, :notice => "Running matching scheduled"
  end
  
  def destroy
    @matching.destroy
    redirect_to matchings_path, :notice => "Matching destroyed"
  end

  protected
  def load_matching
    @matching = Matching.find(params[:id])
  end
end

app/helpers/matchings_helper.rb
module MatchingsHelper
  
  def figure_latex(sketchup)
    "\\includegraphics{models\/#{sketchup.google_id}.jpg}"
  end
end

app/views/matchings/_form.html.haml
= simple_form_for @matching do |f|
  = f.input :name
  = f.association :pointcloud, :as => :select, :collection => Pointcloud.independent
  = f.input :model_name, :as => :select, :collection => Sketchupmodel.all.map { |p| p.name }.uniq
  = f.input :top_models
  .buttons
    = f.submit

app/views/matchings/index.html.haml
%h2 Matchings

.list
  - @matchings.each do |m|
    .list_row
      .list_cell= link_to m.name, m
      .list_cell= link_to "Edit", edit_matching_path(m)
      .list_cell= link_to "Delete", m, :method => :delete

= link_to "New Matching", new_matching_path, :class => "button"

app/views/matchings/new.html.haml
%h2 New Matching

= render :partial => "form"

app/views/matchings/show.html.haml
%h2
  = @matching.name

- if @matching.category == "best_model"
  %p
    %strong Pointcloud Name:
    = @matching.pointcloud.name
- else
  %p
    %strong Scan Name:
    = @matching.scan.name

- if @matching.category == "best_model"
  %p
    %strong Sketchup Model Name:
    = @matching.model_name
- else
  %p
    %strong Sketchup Model Name:
    = @matching.sketchupmodel.name

%p
  %strong Rotation counter
  = @matching.rotation_count
  
%p
  %strong Last Update
  = @matching.updated_at.strftime("%Y-%m-%d %H:%M")

%p
  %strong Now
  = Time.now.strftime("%Y-%m-%d %H:%M")
- unless @matching.results.blank?
  %table
    %tr
      %th Error
      %th Rotation
      %th Model
      %th Actions
    - @matching.sorted_results.each do |r|
      - if @matching.category == "best_model"
        - ms = Sketchupmodel.find_all_by_id(r[1])
        - next if ms.blank?
        - m = ms[0]
        %tr.with_border
          %td= r[0]
          %td= r[2]
          %td
            %center
              = m.name
              %br
              = link_to m do
                = image_tag m.image_link || "http://sketchup.google.com/3dwarehouse/download?mid=#{m.google_id}&rtyp=st&ctyp=other", :class => "sketchup"
          %td
            = link_to new_icp_path(:icp => {:name => "ICP", :first_scan_id => @matching.pointcloud.id, :second_scan_id => m.pointclouds.last.id, :second_scan_rotation => r[2], :parameters => "-a 9 -d 500 -i 500 -r 10 --anim=1"}) do
              See ICP
      - else
        - ps = Pointcloud.find_all_by_id(r[1])
        - next if ps.blank?
        - p = ps[0]
        %tr.with_border
          %td= r[0]
          %td= r[2]
          %td= link_to p.name, p
          %td
            = link_to new_icp_path(:icp => {:name => "ICP", :first_scan_id => p.id, :second_scan_id => @matching.sketchupmodel.pointclouds.last.id, :second_scan_rotation => r[2], :parameters => "-a 9 -d 500 -i 500 -r 10 --anim=1"}) do
              See ICP

%br
= form_tag run_matching_path(@matching) do
  .buttons
    = submit_tag "Run"

app/views/matchings/show.text.erb
\begin{longtable}{ccc}
\caption[<%= @matching.name%>]{<%= @matching.name%>}\\

\multicolumn{1}{c}{\textbf{Error}} & \multicolumn{1}{c}{\textbf{Rotation}} & \multicolumn{1}{c}{\textbf{Google SketchUp model}} \\
\endfirsthead

\multicolumn{3}{c}%
{{\tablename\ \thetable{} -- continued from previous page}} \\
\multicolumn{1}{c}{\textbf{Error}} &
\multicolumn{1}{c}{\textbf{Rotation}} &
\multicolumn{1}{c}{\textbf{Google SketchUp model}} \\
\endhead

\multicolumn{3}{r}{{Continued on next page}} \\
\endfoot

\endlastfoot

<% @matching.sorted_results.each do |r| %>
	<% begin %>
	<%= raw("$#{r[0]}$ & #{r[2]} & #{figure_latex(Sketchupmodel.find(r[1]))}\\\\") %>
	<% rescue %>
	<% end %>
<% end %>
\end{longtable}