config/routes.rb
Slam6DUI::Application.routes.draw do

  resources :pointclouds do
    member do
      post 'slam6d_show'
      post 'scale_and_center'
      post 'reduce'
      post 'convert_to_uos'
      post 'get_object'
      post 'multiply_frames'
      
      get 'webgl'
    end
  end
  
  resources :sketchupmodels  do
    member do
      post "resample"
    end
  end
  resources :matchings do
    member do
      post "run"
    end
  end
  
  resources :icps do
    member do
      get 'run'
      get 'view'
    end
  end
  
  resources :scans do
    member do
      post 'segment'
    end
  end

  root :to => "pointclouds#index"

end

app/models/icp.rb
class Icp < ActiveRecord::Base
  # has_and_belongs_to_many :pointclouds
  belongs_to :first_scan, :class_name => "Pointcloud"
  belongs_to :second_scan, :class_name => "Pointcloud"
  
  PARAMS = ["-a", "-d", "--epsICP", "-f", "-i", "-r"]
   
  def pointclouds
    pc = []
    pc << self.first_scan if self.first_scan
    pc << self.second_scan if self.second_scan
    pc
  end  
  
  # virtual attributes - parameters
  def get_parameter_value(parameter)
    matcher = self.parameters.match("(^|\\s)#{parameter}[\\s=](.+?)($|\\s)")
    return matcher[2] unless matcher.nil?
    return nil
  end
  
  def set_parameter_value(parameter, value)
    prev_value = get_parameter_value(parameter)
    if prev_value
      self.parameters.gsub!("#{parameter} #{prev_value}", "")
      self.parameters.gsub!("#{parameter}=#{prev_value}", "")
    end
    
    if !value.empty?
      new_parameter = "#{parameter}#{parameter[1] == '-' ? '=' : ' '}#{value}"
      self.parameters += " #{new_parameter}"
      self.parameters.gsub!("  ", " ")
    end
  end
  
  def param_a
    get_parameter_value("-a")
  end
  
  def param_a=(value)
    set_parameter_value("-a", value)
  end
  
  def param_d
    get_parameter_value("-d")
  end
  
  def param_d=(value)
    set_parameter_value("-d", value)
  end
  
  def param_r
    get_parameter_value("-r")
  end
  
  def param_r=(value)
    set_parameter_value("-r", value)
  end
  
  def param_i
    get_parameter_value("-i")
  end
  
  def param_i=(value)
    set_parameter_value("-i", value)
  end
  
  def param_epsICP
    get_parameter_value("--epsICP")
  end
  
  def param_epsICP=(value)
    set_parameter_value("--epsICP", value)
  end
end

app/controllers/icps_controller.rb
class IcpsController < ApplicationController
  before_filter :load_icp, :except => [:index, :new, :create]
  
  def index
    @icps = Icp.all
  end
  
  def new
    @icp = Icp.new(params[:icp])
    # @icp.set_parameter_value("--epsICP", "0.0")
    # @icp.set_parameter_value("-i", "3000")
  end
  
  def create
    @icp = Icp.new(params[:icp])
    @icp.save
    redirect_to @icp
  end
  
  def update
    @icp.update_attributes(params[:icp])
    redirect_to @icp
  end
  
  def run
    sl = Slam6D.new({:icp_id => @icp})
    @console_output = sl.runIcp
    render :show
  end
  
  def destroy
    @icp.destroy
    redirect_to icps_path
  end
  
  def view
    render :inline => "View"
  end
  
  protected
  def load_icp
    @icp = Icp.find(params[:id])
  end
end

app/helpers/icps_helper.rb
module IcpsHelper
end

app/views/icps/_form.html.haml
= simple_form_for @icp do |f|
  = f.input :name
  = f.association :first_scan, :as => :select
  = f.association :second_scan, :as => :select
  
  %strong Parameters
  .form_row
    = f.label :param_a, "-a"
    = f.select :param_a, [["unit quaternion based method by Horn", "1"],
                          ["singular value decomposition by Arun et al.", "2"],
                          ["orthonomral matrices by Horn et al.", "3"],
                          ["dual quaternion method by Walker et al.", "4"],
                          ["helix approximation by Hofer & Potmann", "5"],
                          ["small angle approximation", "6"],
                          ["Lu & Milios style - uncertainty based, with Euler angles", "7"],
                          ["Lu & Milios style - uncertainty based, with Quaternion", "8"],
                          ["Unit quaternion with scale method by Horn", "9"]]
    selects the minimization method for the ICP matching algorithm
  .form_row
    = f.label :param_d, "-d"
    = f.text_field :param_d
    sets the maximal point-to-point distance for matching with ICP to <NR> 'units'
  .form_row
    = f.label :param_epsICP, "--epsICP"
    = f.text_field :param_epsICP
    stop ICP iteration if difference is smaller than NR
  .form_row
    = f.label :param_i, "-i"
    = f.text_field :param_i
    sets the maximal number of ICP iterations to <NR>
  .form_row
    = f.label :param_r, "-r"
    = f.text_field :param_r
    turns on octree based point reduction (voxel size <NR>)
    
  %strong Poses
  .form_row
    = f.label :second_scan_position
    = f.text_field :second_scan_position
    (x, y, z)
  .form_row
    = f.label :second_scan_rotation
    = f.text_field :second_scan_rotation
    (xdegree, ydegree, zdegree)
  .buttons
    = f.submit

app/views/icps/edit.html.haml
= render :partial => "form"

app/views/icps/index.html.haml
.list
  - @icps.each do |i|
    .list_row
      .list_cell= link_to i.name, i
      .list_cell= link_to "Edit", edit_icp_path(i)
      .list_cell= link_to "Delete", i, :method => :delete

= link_to "New ICP", new_icp_path, :class => "button"

app/views/icps/new.html.haml
= simple_form_for @icp do |f|
  = f.input :name
  = f.input :parameters
  = f.association :first_scan, :as => :select
  = f.association :second_scan, :as => :select
  .buttons
    = f.submit

app/views/icps/show.html.haml
%p
  %strong Name:
  = @icp.name

%p
  %strong Parameters:
  = @icp.parameters

%p
  %strong Pointclouds:
  = raw(@icp.pointclouds.map { |p| "<u>#{p.name}</u>" }.join(" vs. "))

%br
= link_to "Run", run_icp_path(@icp), :class => "button"
= link_to "Edit", edit_icp_path(@icp), :class => "button"

%br
- if @console_output
  = text_area_tag "console", @console_output, {:size => "150x25"}