config/routes.rb
Slam6DUI::Application.routes.draw do

  resources :pointclouds do
    member do
      post 'slam6d_show'
      post 'scale_and_center'
      post 'reduce'
      post 'convert_to_uos'
      post 'get_object'
      post 'multiply_frames'
      
      get 'webgl'
    end
  end
  
  resources :sketchupmodels  do
    member do
      post "resample"
    end
  end
  resources :matchings do
    member do
      post "run"
    end
  end
  
  resources :icps do
    member do
      get 'run'
      get 'view'
    end
  end
  
  resources :scans do
    member do
      post 'segment'
    end
  end

  root :to => "pointclouds#index"

end

app/models/pointcloud.rb
class Pointcloud < ActiveRecord::Base
  belongs_to :sketchupmodel
  belongs_to :scan
  
  before_destroy :clean_files
  
  scope :independent, :conditions => { :sketchupmodel_id => nil }
  
  def move_to_scan_db(upload)
    `mkdir #{self.directory}`
    File.open(self.complete_path, "wb") { |f| f.write(upload['path'].read) }
  end
  
  def extension
    return ".txt" if self.format == "riegl_txt"    
    ".3d"
  end
  
  def directory
    "#{AppConfig["settings"]["scanDB"]}#{self.id}"
  end
  
  def complete_path
    complete = "#{directory}/scan000#{extension}"
  end
  
  def name
    "#{id} : #{self.label}"
  end
  
  def inverse_transf_matrix
    return nil unless self.transf_matrix
    a = self.transf_matrix.gsub("[", "").gsub("]", "").split(", ").map { |b| b.to_f }
    a[0] = 1 / a[0]
    a[5] = 1 / a[5]
    a[10] = 1 / a[10]
    a[12] = - a[12] * a[0]
    a[13] = - a[13] * a[0]
    a[14] = - a[14] * a[0]
    
    a.to_s
  end
  
  def inverse_times(other)
    a = self.inverse_transf_matrix.gsub("[", "").gsub("]", "").split(", ").map { |b| b.to_f }
    b = other.split(" ")[0..15].map { |a| a.to_f }
  
    # Compute a * b
    a1 = [[a[0], a[4], a[8], a[12]],
          [a[1], a[5], a[9], a[13]],
          [a[2], a[6], a[10], a[14]],
          [a[3], a[7], a[11], a[15]]]
    b1 = [[b[0], b[4], b[8], b[12]],
          [b[1], b[5], b[9], b[13]],
          [b[2], b[6], b[10], b[14]],
          [b[3], b[7], b[11], b[15]]]

    c = 0.upto(3).map { |i| 0.upto(3).map { |j| 0 }}
    0.upto(3) {|i|
      0.upto(3) { |j|
        0.upto(3) { |k|
          c[i][j] += a1[i][k] * b1[k][j]
          }
        }
      }
    
    (0.upto(3).map { |i| 0.upto(3).map { |j| c[j][i] }}.flatten << 1).to_s.gsub("[", "").gsub("]", "").gsub(",", "")
  end
  
  def multiply_inverse(file)
    out = []
    
    in_file = File.new(file, "r")
    while (line = in_file.gets) do
      out << inverse_times(line)
    end
    in_file.close
    
    out_file = File.new(file, "w")
    out.each { |line| out_file.write(line + "\n") }
    out_file.close
  end
  
  def triangleArea(a, b, c)
    (0.5 * (a[0] * b[1] * c[2] + b[0] * c[1] * a[2] + c[0] * a[1] * b[2] - c[0] * b[1] * a[2] - b[0] * a[1] * c[2] - a[0] * c[1] * b[2])).abs
  end
  
  def points_js
    in_file = File.new(self.complete_path, "r")
    points = []
    while(line = in_file.gets) do
      next if line.include?("#")
      point = line.split(" ")
      point = point[0..2] if point.size > 3
      point = point.map { |p| p.to_i }
      points << point
    end
    in_file.close
    
    puts points.size
    points.sort_by {rand}[0..5000].to_json
  end
  
  def resample(points_per_area)
    points = []
    
    puts "Reading points"
    in_file = File.new(self.complete_path, "r")
    while(line = in_file.gets) do
      next if line.include?("#")
      point = line.split(" ")
      point = point[0..2] if point.size > 3
      point = point.map { |p| p.to_f }
      points << point
    end
    in_file.close
    puts "Finished reading #{points.size} points"
    puts "Starting to resample"
    
    final_points = []
    index = 0
    total_slices = points.size / 3
    if points.size < 300000
      points.each_slice(3) do |p|
        index += 1
        final_points << p[0]
        final_points << p[1]
        final_points << p[2]
      
        area = triangleArea(p[0], p[1], p[2])
        0.upto((area * points_per_area).to_i) do |i|
          a = rand()
          b = rand()
          c = 1 - a - b
          while c < 0 do
            a = rand()
            b = rand()
          
            c = 1 - a - b
          end
          r = [a, b, c].shuffle
          a, b, c = r[0], r[1], r[2]
        
          new_point = [p[0][0] * a + p[1][0] * b + p[2][0] * c,
                       p[0][1] * a + p[1][1] * b + p[2][1] * c,
                       p[0][2] * a + p[1][2] * b + p[2][2] * c]
          final_points << new_point
        end
      
        if final_points.size > 600000
          return resample(points_per_area / 10)
        end
      end
    else
      final_points = points
    end
    # final_points.uniq!
    
    puts "writing points = #{final_points.size}"
    p = Pointcloud.create(:label => "#{self.label}, resampled #{points_per_area} points per area unit",
                          :format => "uos")
    `mkdir #{p.directory}`
    File.open("#{p.complete_path}", "w") { |f| f.write(final_points.map { |p| p[0..2].join(" ")}.join("\n")) }
    p
  end
  
  def reduce_with_frequency(frequency = 2)
    p = Pointcloud.create(:name => "#{self.name}, reduced with frequency #{frequency}",
                          :format => self.format)
    `mkdir #{p.directory}`
    
    in_file = File.new(self.complete_path, "r")
    in_file.gets
    
    out_points = []
    line_number = 0
    while (line = in_file.gets) do
      out_points << line if line_number % frequency == 0
      line_number = line_number + 1
    end
    in_file.close
    
    out_file = File.new(p.complete_path, "w")
    out_file.write(out_points.size.to_s + "\n")
    out_points.each { |line| out_file.write(line) }
    out_file.close
    
    p
  end
  
  def convert_to_uos
    p = Pointcloud.create(:name => "#{self.name}", :format => "uos")
    `mkdir #{p.directory}`
    
    in_file = File.new(self.complete_path, "r")
    out_file = File.new(p.complete_path, "w")
    
    line = in_file.gets # skip first line
    while (line = in_file.gets) do
      points = line.split(" ")
      out_file.write(points[0..2].join(" ") + "\n")
    end
        
    out_file.close
    in_file.close
    
    p
  end
  
  def distance_between(p1, p2)
    0.upto(p1.size - 1).map { |i| (p1[i].to_f - p2[i].to_f) ** 2 }.sum
  end
  
  def get_object(center)
    require 'kd-tree'
    
    in_file = File.new(self.complete_path, "r")
    puts "Reading points"
    
    center = center.split(" ")
    points = []
    closest, closest_dist = [], 1000000
    while(line = in_file.gets) do
      next if line.include?("#")
      point = line.split(" ")
      point = point[0..2] if point.size > 3
      point = point.map { |p| p.to_f }
      points << (point + [points.size])
      
      this_distance = distance_between(center, point)
      closest, closest_dist = points.size - 1, this_distance if this_distance < closest_dist
    end
    
    puts "Found closest point to center"
    
    epsilon = 5
    tree = KDTree.new(points, 3)
    puts "Created KD Tree"
  
    v = points.map { |p| false }
    out_points = [points[closest]]
    v[closest] = true
    i = 0
    while(i < out_points.size)
      crt_point = out_points[i]
      ranger = crt_point.map{ |p| [p - epsilon, p + epsilon] }
      new_points = tree.find(ranger[0], ranger[1], ranger[2])
      
      new_points.each do |p|
        unless v[p[3]]
          out_points << p 
          v[p[3]] = true
        end
      end
    
      i += 1
      puts out_points.size
    end

    puts "writing points = #{out_points.size}"
    p = Pointcloud.create(:label => "#{self.label}, points around #{center.join(" ")}, epsilon #{epsilon}",
                          :format => "uos")
    `mkdir #{p.directory}`
    File.open("#{p.complete_path}", "w") { |f| f.write(out_points.map { |p| p[0..2].join(" ")}.join("\n")) }
    p
  end
  
  def switch_y_z
    file = File.new(self.complete_path, "r")
    points = []
    while(line = file.gets)
      next if line.include?("#")
      point = line.split(" ")
      point = point[0..2] if point.size > 3
      point[1], point[2] = point[2], point[1]
      point[1] = -1 * point[1].to_f
      points << point
    end
    
    File.open("#{self.complete_path}", "w") { |f| f.write(points.map { |p| p.join(" ")}.join("\n")) }
  end
  
  def scale_and_center_xyz(base = 500)
    transf = 1.upto(16).map { |i| 0 }
    
    points = []
    file = File.new(self.complete_path, "r")
    n, sumx, sumy, sumz = 0, 0, 0, 0
    while (line = file.gets)
      next if line.include?("#")
      point = line.split(" ")
      point = point[0..2] if point.size > 3
      if point.size == 3
        points << point
        n = n + 1
        sumx += point[0].to_f
        sumy += point[1].to_f
        sumz += point[2].to_f
      end
    end
    file.close
    
    centroidX, centroidY, centroidZ = sumx / n, sumy / n, sumz / n
    maximum = 0
    points.each do |p|
      p[0] = p[0].to_f - centroidX.to_f
      p[1] = p[1].to_f - centroidY.to_f
      p[2] = p[2].to_f - centroidZ.to_f
      maximum = [maximum, p[0].abs, p[1].abs, p[2].abs].max
    end
    
    transf[12] = -centroidX.to_f * base / maximum
    transf[13] = -centroidY.to_f * base / maximum
    transf[14] = -centroidZ.to_f * base / maximum
    transf[15] = 1
    
    points.each do |p|
      p[0] = p[0] * base / maximum
      p[1] = p[1] * base / maximum
      p[2] = p[2] * base / maximum
    end
    
    transf[0] = base / maximum
    transf[5] = base / maximum
    transf[10] = base / maximum
    
    p = Pointcloud.create(:label => "#{self.label}, bounded: #{base}, centered",
                          :format => "uos", :transf_matrix => transf.to_s, :scan_id => self.scan_id,
                          :pointcount => self.pointcount)
    `mkdir #{p.directory}`
    File.open("#{p.complete_path}", "w") { |f| f.write(points.map { |p| p.join(" ")}.join("\n")) }
    p
  end
  
  protected
  def clean_files
    `rm -fdr #{self.directory}`
  end
end

app/controllers/pointclouds_controller.rb
class PointcloudsController < ApplicationController
  
  before_filter :load_pointcloud, :except => [:index, :new, :create]
  
  def index
    @pointclouds = Pointcloud.independent
  end
  
  def webgl
    
  end

  def new
    @pointcloud = Pointcloud.new
  end
  
  def create
    @pointcloud = Pointcloud.new(params[:pointcloud])
    if @pointcloud.save
      flash[:notice] = "Point cloud added successfully."
      @pointcloud.move_to_scan_db(params[:pointcloud])
      redirect_to @pointcloud
    else
      flash[:notice] = "You have some errors.."
      render :new
    end
  end
  
  def multiply_frames
    @pointcloud.multiply_inverse(params[:file_path])
    flash[:notice] = "Multipled frames file by inverse matrix"
    redirect_to @pointcloud
  end
  
  def scale_and_center
    new_p = @pointcloud.scale_and_center_xyz(params[:bounded].to_f)
    redirect_to new_p
  end
  
  def get_object
    new_p = @pointcloud.get_object(params[:center])
    redirect_to new_p
  end
  
  def convert_to_uos
    new_p = @pointcloud.convert_to_uos
    redirect_to new_p
  end
  
  def reduce
    new_p = @pointcloud.reduce_with_frequency(params[:frequency].to_f)
    redirect_to new_p
  end
  
  def slam6d_show
    sl = Slam6D.new({:pointcloud_id => @pointcloud.id})
    @console_output = sl.runShow(params[:reflectance] == "yes")
    render :show
  end
  
  def update
    if @pointcloud.update_attributes(params[:pointcloud])
      flash[:notice] = "Point cloud updated successfully."
      @pointcloud.move_to_scan_db
      redirect_to @pointcloud
    else
      flash[:notice] = "You have some errors.."
      render :edit
    end
  end
  
  def destroy
    @pointcloud.destroy
    redirect_to pointclouds_path
  end
  
  protected
  def load_pointcloud
    @pointcloud = Pointcloud.find(params[:id])
  end

end

app/helpers/pointclouds_helper.rb
module PointcloudsHelper
end

app/views/pointclouds/_convert_to_uos_form.haml
%br
%strong Convert to UOS format
= form_tag convert_to_uos_pointcloud_path(@pointcloud) do
  .buttons
    = submit_tag "Convert"

app/views/pointclouds/_form.html.haml
= form_for @pointcloud, :html => {:multipart => true } do |f|
  .form_row
    = f.label :label
    = f.text_field :label
  .form_row
    = f.label :path
    = f.file_field :path
  .form_row
    = f.label :source
    = f.text_field :source
  .form_row
    = f.label :format
    = f.select :format, ["riegl_txt", "uos", "xyzr"]
  .form_row
    = f.label :description
    = f.text_area :description
  .buttons
    = f.submit

app/views/pointclouds/_pointcloud.html.haml
%p
  %strong Name:
  = pointcloud.name

%p
  %strong Path:
  = pointcloud.complete_path

%p
  %strong Source:
  = pointcloud.source

%p
  %strong Format:
  = pointcloud.format

%p
  %strong Description:
  = pointcloud.description

%p
  %strong Transformation Matrix
  = pointcloud.transf_matrix

%p
  %strong Inverse Transformation Matrix
  = pointcloud.inverse_transf_matrix

%br
%strong Visualize in Slam6D Show Utility
= form_tag slam6d_show_pointcloud_path(pointcloud), :class => "button" do
  .form_row
    = label_tag "Reflectance"
    = check_box_tag "reflectance", "yes", true
  .buttons
    = submit_tag "Show"

%br
%strong Multiply frames file with inverse matrix
= form_tag multiply_frames_pointcloud_path(pointcloud), :class => "button" do
  .form_row
    = label_tag "File Name"
    = text_field_tag "file_path", "#{AppConfig["settings"]["slam6dPath"]}dat/ui/scan001.frames", :size => 100
  .buttons
    = submit_tag "Multiply"

app/views/pointclouds/_reduce_form.haml
%br
%strong Reduce Pointcloud
= form_tag reduce_pointcloud_path(@pointcloud) do
  .form_row
    = label_tag "frequency"
    = text_field_tag "frequency", 3
    Keep 1 out of [x] points in pointcloud
  .buttons
    = submit_tag "Reduce"

app/views/pointclouds/_scale_and_center_form.html.haml
%br
%strong Scale and Center Pointcloud
= form_tag scale_and_center_pointcloud_path(@pointcloud) do
  .form_row
    = label_tag "All coordinates smaller than"
    = text_field_tag "bounded", 500
  .buttons
    = submit_tag "Scale and Center"

app/views/pointclouds/_segment_object_form.html.haml
%br
%strong Get Object Around Point
= form_tag get_object_pointcloud_path(@pointcloud) do
  .form_row
    = label_tag "Base Point"
    = text_field_tag "center", "0 0 0"
  .buttons
    = submit_tag "Get Object"

app/views/pointclouds/edit.html.haml
%h2 Edit Point Cloud

= render :partial => "form"

app/views/pointclouds/index.html.haml
.list
  - @pointclouds.each do |p|
    .list_row
      .list_cell= link_to p.name, p
      .list_cell= p.format
      .list_cell= link_to "Edit", edit_pointcloud_path(p)
      .list_cell= link_to "Delete", p, :method => :delete


= link_to "New Point Cloud", new_pointcloud_path, :class => "button"

app/views/pointclouds/new.html.haml
New Point Cloud

= form_for @pointcloud do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :path
    = f.text_field :path
  %p
    = f.label :source
    = f.text_field :source
  %p
    = f.label :format
    = f.select :format, ["Riegl", "3D Warehouse"]
  %p
    = f.label :description
    = f.text_area :description
  %p
    = f.submit

app/views/pointclouds/show.html.haml
= render :partial => @pointcloud

- if ["uos", "xyzr"].include? @pointcloud.format
  = render :partial => "scale_and_center_form"

- if ["riegl_txt"].include? @pointcloud.format
  = render :partial => "reduce_form"

- if ["riegl_txt"].include? @pointcloud.format
  = render :partial => "convert_to_uos_form"

- if ["uos", "xyzr"].include? @pointcloud.format
  = render :partial => "segment_object_form"

- if @console_output
  = text_area_tag "console", @console_output, {:size => "150x25"}

= link_to "See", webgl_pointcloud_path(@pointcloud)

app/views/pointclouds/webgl.html.haml
:javascript
  var points = #{@pointcloud.points_js};
  var container, stats;
  var camera, scene, renderer, particle;
  var mouseX = 0, mouseY = 0;

  var windowHalfX = window.innerWidth / 2;
  var windowHalfY = window.innerHeight / 2;

  init();
  animate();
  
  function init() {
    container = document.createElement( 'div' );
    document.body.appendChild( container );

    camera = new THREE.Camera( 75, window.innerWidth / window.innerHeight, 1, 10000 );
    camera.position.z = 1000;

    scene = new THREE.Scene();

    var PI2 = Math.PI * 2;
    var material = new THREE.ParticleCanvasMaterial( {
    	color: 0x000000,
    	program: function ( context ) {
    		context.beginPath();
    		context.arc( 0, 0, 2, 0, PI2, true );
    		context.closePath();
    		context.fill();
    	}
    } );

    for (var i = 0; i < points.length; i++) {
    	particle = new THREE.Particle( material );
    	particle.position.x = points[i][0];
    	particle.position.y = points[i][1];
    	particle.position.z = points[i][2];
    	scene.addObject( particle );
    }

    renderer = new THREE.CanvasRenderer();
    renderer.setSize( window.innerWidth, window.innerHeight );
    container.appendChild( renderer.domElement );

    document.addEventListener( 'mousemove', onDocumentMouseMove, false );
    document.addEventListener( 'touchstart', onDocumentTouchStart, false );
    document.addEventListener( 'touchmove', onDocumentTouchMove, false );
  }
  
  function onDocumentMouseMove(event) {
  	mouseX = event.clientX - windowHalfX;
  	mouseY = event.clientY - windowHalfY;
  }

  function onDocumentTouchStart( event ) {
  	if ( event.touches.length > 1 ) {
  		event.preventDefault();
  		mouseX = event.touches[ 0 ].pageX - windowHalfX;
  		mouseY = event.touches[ 0 ].pageY - windowHalfY;
  	}
  }

  function onDocumentTouchMove( event ) {
  	if ( event.touches.length == 1 ) {
  		event.preventDefault();
  		mouseX = event.touches[ 0 ].pageX - windowHalfX;
  		mouseY = event.touches[ 0 ].pageY - windowHalfY;
  	}
  }
  
  function render() {
    camera.position.x += ( mouseX - camera.position.x ) * .05;
    camera.position.y += ( - mouseY - camera.position.y ) * .05;

    renderer.render( scene, camera );
  }
  
  function animate() {
    requestAnimationFrame(animate);
    render();
  }
/
  :javascript
    var points = #{@pointcloud.points_js};
    var camera, scene, renderer,
    geometry, material, mesh;

    init();
    render();
    // animate();

    function init() {

        camera = new THREE.Camera( 75, window.innerWidth / window.innerHeight, 1, 10000 );
        camera.position.z = 1000;

        scene = new THREE.Scene();
      
        for (var i = 0; i < points.length; i++) {
          geometry = new Sphere(1, 1);
          material = new THREE.MeshBasicMaterial( { color: 0xff0000, wireframe: true } );

          mesh = new THREE.Mesh( geometry, material );
          mesh.position.x = points[i][0];
          mesh.position.y = points[i][1];
          mesh.position.z = points[i][2];
          scene.addObject( mesh );
        }

        renderer = new THREE.CanvasRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );

        document.body.appendChild( renderer.domElement );

    }

    function animate() {

        // Include examples/js/RequestAnimationFrame.js for cross-browser compatibility.
        requestAnimationFrame( animate );
        render();

    }

    function render() {

        mesh.rotation.x += 0.01;
        mesh.rotation.y += 0.02;

        renderer.render( scene, camera );

    }