config/routes.rb
Slam6DUI::Application.routes.draw do

  resources :pointclouds do
    member do
      post 'slam6d_show'
      post 'scale_and_center'
      post 'reduce'
      post 'convert_to_uos'
      post 'get_object'
      post 'multiply_frames'
      
      get 'webgl'
    end
  end
  
  resources :sketchupmodels  do
    member do
      post "resample"
    end
  end
  resources :matchings do
    member do
      post "run"
    end
  end
  
  resources :icps do
    member do
      get 'run'
      get 'view'
    end
  end
  
  resources :scans do
    member do
      post 'segment'
    end
  end

  root :to => "pointclouds#index"

end

app/models/sketchupmodel.rb
class Sketchupmodel < ActiveRecord::Base
  has_many :pointclouds, :dependent => :destroy
  accepts_nested_attributes_for :pointclouds
  
  def google_link
    "http://sketchup.google.com/3dwarehouse/details?mid=#{google_id}"
  end
  
  def resample(points_per_area)
    self.pointclouds.last.destroy if self.pointclouds.size >= 3
    
    puts "Model #{id}"
    p = pointclouds[1].resample(points_per_area)
    self.pointclouds << p
    save
  end
  
  def add_scaled_and_centered
    self.pointclouds << self.pointclouds.first.scale_and_center_xyz(500)
    save
  end
  
  def self.schedule_resampling
    Sketchupmodel.all.each { |s| s.delay.resample(0.0005) }
  end
  
  def download
    `wget "http://sketchup.google.com/3dwarehouse/download?mid=#{self.google_id}&rtyp=st&ctyp=other" -O ~/Desktop/models/#{self.google_id}.jpg`
  end
  
  def self.download_all
    Sketchupmodel.all.each do |s|
      s.download
    end
  end
end

app/controllers/sketchupmodels_controller.rb
class SketchupmodelsController < ApplicationController
  before_filter :load_sketchupmodel, :except => [:new, :create, :index]
  skip_before_filter :verify_authenticity_token, :only => [:create]
  
  def update
    if @model.update_attributes(params[:sketchupmodel])
      flash[:notice] = "Sketchup model updated successfully."
      redirect_to sketchupmodels_path
    else
      flash[:notice] = "You have some errors.."
      render :new
    end
  end
  
  def new
    @model = Sketchupmodel.new(:name => "Audi A4")
    @model.pointclouds.build(:format => "uos")
  end
  
  def resample
    @model.resample(params[:points_per_area].to_f)
    redirect_to @model, :notice => "Resampled"
  end
  
  def create
    @model = Sketchupmodel.new(params[:sketchupmodel])
    if @model.save
      @model.pointclouds.first.move_to_scan_db(params[:sketchupmodel][:pointclouds_attributes]["0"])
      @model.update_attribute(:google_id, params[:sketchupmodel][:pointclouds_attributes]["0"]['path'].original_filename.gsub(".3d", "").split("_")[0])
      
      @model.pointclouds.map { |p| p.update_attribute(:label, @model.name) }
      @model.delay.add_scaled_and_centered
      
      flash[:notice] = "Sketchup model saved successfully."
      redirect_to sketchupmodels_path
    else
      flash[:notice] = "You have some errors.."
      render :new
    end
  end
  
  def destroy
    @model.destroy
    redirect_to sketchupmodels_path
  end
  
  def index
    @models = Sketchupmodel.all
  end
  
  protected
  def load_sketchupmodel
    @model = Sketchupmodel.find(params[:id])
  end
end

app/helpers/sketchupmodels_helper.rb
module SketchupmodelsHelper
end

app/views/sketchupmodels/_form.html.haml
= form_for @model, :html => {:multipart => true } do |f|
  .form_row
    = f.label :name
    = f.text_field :name
  - f.fields_for :pointclouds do |p|
    .form_row
      = p.label :path
      = p.file_field :path
    = p.hidden_field :format
  .buttons
    = f.submit

app/views/sketchupmodels/index.html.haml
%h2 Sketchup Models

.list
  - @models.each do |p|
    .list_row
      .list_cell= p.id
      .list_cell= link_to p.name, p
      .list_cell= link_to p.google_id, p.google_link
      .list_cell= link_to "Edit", edit_sketchupmodel_path(p)
      .list_cell= link_to "Delete", p, :method => :delete
      .list_cell
        = image_tag "http://sketchup.google.com/3dwarehouse/download?mid=#{p.google_id}&rtyp=st&ctyp=other"
        
= link_to "New Google Sketchup Model", new_sketchupmodel_path, :class => "button"

app/views/sketchupmodels/new.html.haml
%h2 New Sketchup Model

= render :partial => "form"

app/views/sketchupmodels/show.html.haml
%h2
  = @model.name
  [
  = link_to @model.google_id, @model.google_link
  ]

.list
  - @model.pointclouds.each do |p|
    .list_row
      .list_cell
        = link_to p.name, p
      .list_cell
        = link_to "Delete", p, :method => :delete
        

%br
%strong Resample Model
= form_tag resample_sketchupmodel_path(@model) do
  .form_row
    = label_tag "Points per Area Unit"
    = text_field_tag "points_per_area", "0.0001"
  .buttons
    = submit_tag "Resample"